<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDiaecbh\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDiaecbh/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDiaecbh.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDiaecbh\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDiaecbh\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Diaecbh',
    'container.build_id' => 'a187236b',
    'container.build_time' => 1548539600,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDiaecbh');
